[theme]
base = "light"
# Primary accent color.
primaryColor = "#3797E0"
# Background color of the app.
backgroundColor = "#FFFFFF"
# Background color used for most interactive widgets.
secondaryBackgroundColor = "#F0F2F6"
# Color used for almost all text.
textColor = "#222222"
font = "monospace"


[theme.sidebar]
# Primary accent color.
primaryColor = "#2e2e3a"
# Background color of the app.
backgroundColor = "#6D8A96"
# Background color used for most interactive widgets.
secondaryBackgroundColor = "#bc5d2e"
